import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Nav } from '../sections'
import { Toaster } from '@/components/ui'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`flex max-h-screen min-h-screen flex-col relative ${inter.className}`}>
        <Nav />
        {children}
        <Toaster />
      </body>
    </html>
  )
}
