export { Welcome } from './Welcome'
export { Info } from './Info'
export { Catalogue } from './Catalogue'
export { SlidingSection } from './SlidingSection'
export { Footer } from './Footer'
export { AdminNav } from './AdminNav'