export { Nav } from './Nav'
export { Welcome } from './Welcome'
export { Info } from './Info'
export { Catalogue } from './Catalogue'
export { PicPreview } from './PicPreview'
export { Footer } from './Footer'
export { AdminNav } from './AdminNav'